### ISSUE TITLE
Auto fish not working

### ISSUE THREAD

**Issue by Thunder33345** [Team-Pepsi/pepsimod#3] opened 2017-12-20 16:24 UTC
what i expected: it to cast the rod and wind when it caught something
what i get: the rod keep begin casted and winded without catching anything

**Comment by SuperOP535** [comment] 2017-12-21 09:55
probz combat fishing

**Comment by Thunder33345** [comment] 2017-12-21 10:26
nope, it works fine if i cast the rod and enable the mod
but that only work for the first fish

**Comment by DaMatrix** [comment] 2019-04-27 11:13
Unable to reproduce, and this issue is old. Closing!

**Closed by DaMatrix** 2019-04-27 11:13 UTC
Labels: bug, invalid
